services:
  frontend:
    build:
      context: ./frontend
      target: prod
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    env_file:
      - ./backend/.env.db
    ports:
      - "6543:5432"
    volumes:
      - ./backend/data:/var/lib/postgresql/data
