version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: frontend
    command: yarn dev
    restart: always
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      target: dev
    container_name: backend
    command: pipenv run dev
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    env_file:
      - ./backend/.env.db
    ports:
      - "6543:5432"
    volumes:
      - ./backend/data:/var/lib/postgresql/data
