version: "3.8"
name: evergreen

services:
  frontend:
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres:15
    restart: always
    env_file:
      - ./data/.env.db
    ports:
      - "6543:5432"
    volumes:
      - ./data/prod:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 6544:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - database

volumes:
  pgadmin:
