services:
  frontend:
    build:
      context: ./frontend
      target: prod
    container_name: frontend
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    container_name: backend
    command: pipenv run dev
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9713
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
