"""empty message

Revision ID: 33b48d8cccec
Revises: 24609a1f2868
Create Date: 2024-06-24 13:44:31.994267

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "33b48d8cccec"
down_revision: Union[str, None] = "24609a1f2868"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "SelfHostedGroup",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["Account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("SystemInfo")
    op.drop_table("MonitoringPostgres")
    op.add_column("FileRecord", sa.Column("src", sa.String(), nullable=True))
    op.alter_column("FileRecord", "type", new_column_name="record_type")
    op.drop_index("ix_FileRecord_type", table_name="FileRecord")
    op.create_index(
        op.f("ix_FileRecord_record_type"), "FileRecord", ["record_type"], unique=False
    )
    op.add_column("SelfHosted", sa.Column("group_id", sa.Integer(), nullable=True))
    op.drop_constraint("SelfHosted_account_id_fkey", "SelfHosted", type_="foreignkey")
    op.create_foreign_key(None, "SelfHosted", "SelfHostedGroup", ["group_id"], ["id"])
    op.drop_column("SelfHosted", "account_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "SelfHosted",
        sa.Column("account_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "SelfHosted", type_="foreignkey")
    op.create_foreign_key(
        "SelfHosted_account_id_fkey", "SelfHosted", "Account", ["account_id"], ["id"]
    )
    op.drop_column("SelfHosted", "group_id")
    op.drop_column("Monitoring", "status")
    op.alter_column("FileRecord", "record_type", new_column_name="type")
    op.drop_index(op.f("ix_FileRecord_record_type"), table_name="FileRecord")
    op.create_index("ix_FileRecord_type", "FileRecord", ["type"], unique=False)
    op.drop_column("FileRecord", "src")
    op.create_table(
        "MonitoringPostgres",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text(
                "nextval('\"MonitoringPostgres_id_seq\"'::regclass)"
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "connection_string", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("query", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("monitoring_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["monitoring_id"],
            ["Monitoring.id"],
            name="MonitoringPostgres_monitoring_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="MonitoringPostgres_pkey"),
        sa.UniqueConstraint(
            "monitoring_id", name="MonitoringPostgres_monitoring_id_key"
        ),
    )
    op.create_table(
        "SystemInfo",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"SystemInfo_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("device_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("cpu", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("memory", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="SystemInfo_pkey"),
    )
    op.drop_table("SelfHostedGroup")
    # ### end Alembic commands ###
