"""empty message

Revision ID: 46bfda884c3d
Revises: eb7a980fc4d9
Create Date: 2024-06-30 13:19:12.753314

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46bfda884c3d"
down_revision: Union[str, None] = "eb7a980fc4d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "Monitoring_self_hosted_id_fkey",
        "Monitoring",
    )
    op.drop_constraint(
        "Files_self_hosted_id_fkey",
        "Files",
    )
    op.alter_column(
        "SelfHosted",
        "id",
        existing_type=sa.UUID(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "Files",
        "self_hosted_id",
        existing_type=sa.UUID(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "Monitoring",
        "self_hosted_id",
        existing_type=sa.UUID(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.create_foreign_key(
        "Monitoring_self_hosted_id_fkey",
        "Monitoring",
        "SelfHosted",
        ["self_hosted_id"],
        ["id"],
    )
    op.create_foreign_key(
        "Files_self_hosted_id_fkey",
        "Files",
        "SelfHosted",
        ["self_hosted_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "Files_self_hosted_id_fkey",
        "Files",
    )
    op.drop_constraint(
        "Monitoring_self_hosted_id_fkey",
        "Monitoring",
    )
    op.alter_column(
        "SelfHosted",
        "id",
        existing_type=sa.String(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "Monitoring",
        "self_hosted_id",
        existing_type=sa.String(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "Files",
        "self_hosted_id",
        existing_type=sa.String(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.create_foreign_key(
        "Monitoring_self_hosted_id_fkey",
        "Monitoring",
        "SelfHosted",
        ["self_hosted_id"],
        ["id"],
    )
    op.create_foreign_key(
        "Files_self_hosted_id_fkey",
        "Files",
        "SelfHosted",
        ["self_hosted_id"],
        ["id"],
    )

    # ### end Alembic commands ###
