"""empty message

Revision ID: 64404df35574
Revises: 33b48d8cccec
Create Date: 2024-06-24 14:15:47.513449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64404df35574"
down_revision: Union[str, None] = "33b48d8cccec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Records",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["Account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Records_status"), "Records", ["status"], unique=False)
    op.create_index(op.f("ix_Records_type"), "Records", ["type"], unique=False)
    op.create_table(
        "Files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("src", sa.String(), nullable=True),
        sa.Column("record_id", sa.String(), nullable=True),
        sa.Column("self_hosted_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["Records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["self_hosted_id"],
            ["SelfHosted.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("Resume", sa.Column("record_id", sa.String(), nullable=True))
    op.create_foreign_key(None, "Resume", "Records", ["record_id"], ["id"])
    op.execute(
        """
        INSERT INTO "Records" (id, status, type, created_at, account_id)
        SELECT id, status, record_type, created_at, account_id FROM "FileRecord"
        """
    )
    op.execute(
        """
        INSERT INTO "Files" (name, size, type, src, record_id, self_hosted_id)
        SELECT filename, filesize, filetype, src, id, self_hosted_id FROM "FileRecord"
        """
    )
    op.execute(
        """
        UPDATE "Resume" SET record_id =
        (SELECT id FROM "FileRecord" WHERE "FileRecord".id = "Resume".file_record_id)
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, "Resume", type_="foreignkey")
    op.drop_column("Resume", "record_id")
    op.drop_table("Files")
    op.drop_index(op.f("ix_Records_type"), table_name="Records")
    op.drop_index(op.f("ix_Records_status"), table_name="Records")
    op.drop_table("Records")
    # ### end Alembic commands ###
