"""empty message

Revision ID: 708e19b4e768
Revises: 64404df35574
Create Date: 2024-06-24 14:22:48.047011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "708e19b4e768"
down_revision: Union[str, None] = "64404df35574"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_FileRecord_filename", table_name="FileRecord")
    op.drop_index("ix_FileRecord_record_type", table_name="FileRecord")
    op.drop_index("ix_FileRecord_status", table_name="FileRecord")
    op.drop_constraint("Resume_file_record_id_fkey", "Resume", type_="foreignkey")
    op.drop_column("Resume", "file_record_id")
    op.drop_column("Resume", "updated_at")
    op.drop_table("FileRecord")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "FileRecord",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("filesize", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("filetype", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("record_type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("account_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("self_hosted_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("src", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"], ["Account.id"], name="FileRecord_account_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["self_hosted_id"], ["SelfHosted.id"], name="FileRecord_self_hosted_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="FileRecord_pkey"),
    )
    op.create_index("ix_FileRecord_status", "FileRecord", ["status"], unique=False)
    op.create_index(
        "ix_FileRecord_record_type", "FileRecord", ["record_type"], unique=False
    )
    op.create_index("ix_FileRecord_filename", "FileRecord", ["filename"], unique=False)
    op.add_column(
        "Resume",
        sa.Column("file_record_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "Resume",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            server_default=sa.text("now()"),
        ),
    )
    op.create_foreign_key(
        "Resume_file_record_id_fkey", "Resume", "FileRecord", ["file_record_id"], ["id"]
    )
    pass
    # ### end Alembic commands ###
