"""empty message

Revision ID: ea9fcf24485f
Revises: 46bfda884c3d
Create Date: 2024-06-30 16:12:52.851894

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ea9fcf24485f"
down_revision: Union[str, None] = "46bfda884c3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("SelfHosted", sa.Column("account_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "SelfHosted", "Account", ["account_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("SelfHosted_account_id_fkey", "SelfHosted", type_="foreignkey")
    op.drop_column("SelfHosted", "account_id")
    # ### end Alembic commands ###
