"""empty message

Revision ID: eb7a980fc4d9
Revises: 708e19b4e768
Create Date: 2024-06-29 18:49:40.044551

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb7a980fc4d9"
down_revision: Union[str, None] = "708e19b4e768"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "SelfHostedGroup", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "SelfHostedGroup", type_="unique")
    # ### end Alembic commands ###
