"""empty message

Revision ID: c3981a8059d7
Revises: 105840cbdd50
Create Date: 2024-05-26 19:49:32.719935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3981a8059d7'
down_revision: Union[str, None] = '105840cbdd50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FileRecord', sa.Column('filename', sa.String(), nullable=True))
    op.add_column('FileRecord', sa.Column('filesize', sa.Integer(), nullable=True))
    op.drop_column('FileRecord', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FileRecord', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('FileRecord', 'filesize')
    op.drop_column('FileRecord', 'filename')
    # ### end Alembic commands ###
