#!/bin/bash
{
  echo "FRONTEND_URL=$FRONTEND_URL"
  echo "SECRET_TOKEN=$SECRET_TOKEN"
  echo "SECRET_ANSWER=$SECRET_ANSWER"
  echo "SUPPORT_EMAIL_ADDRESS=$SUPPORT_EMAIL_ADDRESS"
  echo "SUPPORT_EMAIL_PASSWORD=$SUPPORT_EMAIL_PASSWORD"
  echo "DATABASE_URL=$DATABASE_URL"
  echo "MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY"
  echo "MINIO_SECRET_KEY=$MINIO_SECRET_KEY"
  echo "MINIO_URL=$MINIO_URL"
  echo "POSTGRES_USER=$POSTGRES_USER"
  echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
  echo "POSTGRES_DB=$POSTGRES_DB"
  echo "POSTGRES_HOST=$POSTGRES_HOST"
} >>./backend/.env
