name: CI/CD

on:
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./

jobs:
  code-quality-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd backend
          python3 -m pip install --upgrade pipenv
          pipenv install --dev

      - name: Run linters
        run: |
          cd backend
          pipenv run typecheck

  code-quality-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies and run linters
        run: |
          cd frontend
          yarn install
          yarn lint
